import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='bg-mainLight dark:bg-mainBlack'>
        <div className='flex h-screen justify-center flex-col gap-6 mx-auto p-6 items-center max-w-lg'>
          <div className='flex w-full mx-auto  bg-blue items-center outline-none '>
            Hello
          </div>
        </div>
      </div>
    </div>
  );
}
