import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='bg-mainLight dark:bg-mainBlack'>
        <div className='home flex flex-col mx-auto  items-center  max-w-5xl bg-mainLight'>
          <div className='flex w-full mx-auto  bg-blue items-center outline-none '>
            Hello
          </div>
        </div>
      </div>
    </div>
  );
}
